APRS_SERVER_HOST = 'aprs.glidernet.org'
APRS_SERVER_PORT_FULL_FEED = 10152
APRS_SERVER_PORT_CLIENT_DEFINED_FILTERS = 14580

APRS_APP_NAME = 'aogn'
PACKAGE_VERSION = '0.1.0'
APRS_APP_VER = PACKAGE_VERSION[:3]

APRS_KEEPALIVE_TIME = 120
